- Makefile
- ambari-logsearch-logfeeder/src/main/scripts/logfeeder.sh
- ambari-logsearch-server/src/main/scripts/logsearch.sh
- pom.xml
Use JDK8 by default instead of JDK11 (also reverts some gc jvm settings because of this)
started on docker env
please review @kasakrisz @swagle @g-boros @adoroszlai
> AMBARI-24692. Use jdk8 as default compiler version

- ambari-logsearch-server/pom.xml
- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/common/ApiDocStorage.java
- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/rest/AuditLogsResource.java
- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/rest/EventHistoryResource.java
- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/rest/ServiceLogsResource.java
- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/rest/ShipperConfigResource.java
- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/rest/StatusResource.java
- ambari-logsearch-server/src/main/resources/swagger/swagger.html
Upgrade swagger-ui to 3.19.0
Manually:
1. Start Logsearch Server in idea
2. In a browser in incognito mode navigate to the page: http://localhost:61888/docs
3. Try the APIs like `info` and `status`
4. Try to authenticate using the default logsearh admin credentials and try the APIs again
> AMBARI-24802 - Logsearch: upgrade swagger-ui to 3.19.0

- Makefile
- README.md
- ambari-logsearch-appender/pom.xml
- ambari-logsearch-assembly/pom.xml
- ambari-logsearch-config-api/pom.xml
- ambari-logsearch-config-json/pom.xml
- ambari-logsearch-config-local/pom.xml
- ambari-logsearch-config-solr/pom.xml
- ambari-logsearch-config-zookeeper/pom.xml
- ambari-logsearch-it/pom.xml
- ambari-logsearch-log4j2-appender/pom.xml
- ambari-logsearch-logfeeder-container-registry/pom.xml
- ambari-logsearch-logfeeder-plugin-api/pom.xml
- ambari-logsearch-logfeeder/pom.xml
- ambari-logsearch-server/pom.xml
- ambari-logsearch-web/pom.xml
- pom.xml
Define maven version in one place.
Log Search requires maven 3.5.x, from that point for dev build.(note that, and upgrade to that version)
On releng side, if they are using maven versions:set, that would override the ${revision} properties everywhere, that means, with that way, maven 3.3.9 can still build the project
manually with different maven commands
> Update maven versioning

- README.md
Fix typo in README for instructions to "Update version".
```bash
$ make -n set-version new-version="2.8.0.0-11"
make: *** No rule to make target `set-version'.  Stop.
```
```bash
$ make -n update-version new-version="2.8.0.0-11"
mvn versions:set -DnewVersion=2.8.0.0-11 -DgenerateBackupPoms=false
```
> Make rule to set version is `update-version`, not `set-version`

- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputFile.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputHDFSFile.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputS3File.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/spool/LogSpooler.java
- ambari-logsearch-logfeeder/src/main/scripts/logfeeder.sh
- ambari-logsearch-server/src/main/scripts/logsearch.sh
- docker/cloud-docker-compose.yml
- docker/test-config/logfeeder/shipper-conf/output.config.json
currently hdfs/s3 otuputs are not working properly, they are just open an empty file, i wont do anything.
as i see all kind of logs are written to the same output, so in the future we should change the log spooler to have a local file per service log
also added a new docker compose file with hdfs and s3 as well
+ fixing issue with debug java processes (use * pattern, to make it work remotely)
hdfs looking good, s3 has problems with the trustmanager with jdk 10/11, i will continue to take a look on that. probably that will be only a problem with the docker env
Please review @g-boros
> AMBARI-24825. Log Feeder: Fix HDFS/S3 outputs

- ambari-logsearch-server/src/main/scripts/logsearch.sh
Logsearch server can not be started in debug mode if Logsearch is running in an Ambari managed cluster using java 8
manually:
1. Start Logsearch using the docker env and attach a debugger
2. Deploy Ambari and Logsearch, enable debug mode in logsearch-env and attach a debugger
> AMBARI-24851 - Logsearch: debug mode using java 8 and 11

- .gitignore
- pom.xml
Use flatten plugin for building the project, as without that the sub-modules cannot be built separately (because of revision property)
i could build any submodule
> AMBARI-24875. Log Search: cannot build sub-modules separately.

- ambari-logsearch-it/pom.xml
- ambari-logsearch-it/src/test/java/org/apache/ambari/logsearch/solr/Solr.java
- ambari-logsearch-it/src/test/java/org/apache/ambari/logsearch/solr/SolrDocumentMatcher.java
- ambari-logsearch-it/src/test/java/org/apache/ambari/logsearch/solr/search/SearchServiceLogsTest.java
- ambari-logsearch-server/src/main/configsets/audit_logs/conf/managed-schema
- ambari-logsearch-server/src/main/configsets/hadoop_logs/conf/managed-schema
- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/converter/AbstractDateRangeFacetQueryConverter.java
- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/converter/AbstractOperationHolderConverter.java
- ambari-logsearch-web/src/app/services/logs-filtering-utils.service.ts
- On Logsearch UI if a sentence like "Some terrible error has happened" is used for message filtering a huge amount of irrelevant log entries is pulled, this is mainly because the search term is tokenized and finds every line that contains any of the words.
- The UI replaces all whitespace characters in the search terms to `+` char. It is a boolean operator: The `+` symbol (also known as the "required" operator) requires that the term after the `+` symbol exist somewhere in a field in at least one document in order for the query to return a match.
- Special solr query characters can not be used in search terms because the log_message field is tokenized by StandardTokenizer and it eliminates the special characters.
Fix.: 
- switch to WhiteSpaceTokenizer for log_message field.
- do not …
> AMBARI-24847 - Logsearch: Cannot search for a term that includes spaces or dashes

- ambari-logsearch-web/src/app/components/action-menu/action-menu.component.ts
- ambari-logsearch-web/src/app/components/filter-button/filter-button.component.ts
- ambari-logsearch-web/src/app/components/menu-button/menu-button.component.html
- ambari-logsearch-web/src/app/components/menu-button/menu-button.component.ts
- ambari-logsearch-web/src/app/modules/shared/components/dropdown-button/dropdown-button.component.html
- ambari-logsearch-web/src/app/modules/shared/components/dropdown-button/dropdown-button.component.ts
- ambari-logsearch-web/src/app/modules/shared/components/dropdown-list/dropdown-list.component.ts
- ambari-logsearch-web/src/app/modules/shared/components/filter-dropdown/filter-dropdown.component.ts
The default selection has not been set by the parent component (ActionMenuComponent). This auto selection has been added to the `ngOnInit`.
It was tested manually and by unit tests:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 292 of 292 SUCCESS (11.807 secs / 11.638 secs)
✨  Done in 39.18s.
```
> [AMBARI-24891] [Log Serach UI] The Log Index Filter panel does not work

- ambari-logsearch-config-local/src/main/java/org/apache/ambari/logsearch/config/local/LogSearchConfigLogFeederLocal.java
- ambari-logsearch-config-zookeeper/src/main/java/org/apache/ambari/logsearch/config/zookeeper/LogLevelFilterManagerZK.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/common/LogFeederConstants.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/LogFeederProps.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/manager/operations/impl/AbstractInputConfigHandler.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/manager/operations/impl/CloudStorageInputConfigHandler.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/manager/operations/impl/DefaultInputConfigHandler.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputLineEnricher.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputManagerImpl.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageLoggerFactory.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageOutputManager.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageUploader.java
- ambari-logsearch-logfeeder/src/main/resources/logfeeder.properties
- optionally use filters (+ json output) for logs that will be archived to cloud storage (default: false)
- create output enricher class - only extend common operations there (there is not any refactor there) 
FT: manually
> AMBARI-24833. Support for cloud logs to using filters + JSON output

- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageLoggerFactory.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageUploader.java
Use hostname + cluster name as well in archive dir (to make it work properly with mounts)
FT manually with docker env
> AMBARI-24833. Use clustername and hostname in cloud log archive dir

- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/HDFSS3UploadClient.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/HDFSUploadClient.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/util/LogFeederHDFSUtil.java
- ambari-logsearch-logfeeder/src/main/resources/logfeeder.properties
core site configs can be override by logfeeder.properties.
It can be useful if no core-site.xml available on a host
FT: manually
> AMBARI-24833. Let logfeeder.properties override core-site configs.

- ambari-logsearch-web/src/app/components/filters-panel/filters-panel.component.less
- ambari-logsearch-web/src/app/components/log-index-filter/log-index-filter.component.less
- ambari-logsearch-web/src/app/components/logs-container/logs-container.component.less
- ambari-logsearch-web/src/app/components/logs-container/logs-container.component.ts
- ambari-logsearch-web/src/app/modules/shared/components/dropdown-list/dropdown-list.component.less
I removed the JavaScript scroll listener and changed to the `position: sticky` solution since the only browser which does not support is IE11 but even there the functionality won't break at all.
It was tested manually, and by running unit tests:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 292 of 292 SUCCESS (15.13 secs / 14.97 secs)
✨  Done in 45.62s.
```
> [AMBARI-24882] [Log Search UI] Change sticky filter panel solution from JS to clean css.

- ambari-logsearch-config-local/src/main/java/org/apache/ambari/logsearch/config/local/LogSearchConfigLogFeederLocal.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/common/LogFeederConstants.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/LogFeederProps.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageOutput.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageUploader.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/upload/HDFSUploadClient.java
Do not create FS on main thread, on hybrid mode, it can block the main thread so the solr output will stop working.
also adding a timeout for cloud log uploader (for uploading + fs creation)
stopped localstack/hdfs in hybrid mode
Please review @g-boros
> AMBARI-24833. Do not open FS on main thread.

- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/conf/LogSearchHttpConfig.java
- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/conf/LogSearchWebServerCustomizer.java
- ambari-logsearch-server/src/main/resources/log4j2.yml
Add jetty access logs for Log Search.
Try to gather log-path property from log4j2 config, and use that as the directory for the jetty access log
Manually
> AMBARI-24935. Log Search: enable/disable request audit logging for jetty

- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/loglevelfilter/LogLevelFilterHandler.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputLineEnricher.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputManagerImpl.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputSolr.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/cloud/CloudStorageOutputManager.java
- docker/test-config/logfeeder/shipper-conf/input.config-grafana.json
- docker/test-logs/grafana/grafana.log
- use UNKNOWN level for parse errors
- use UNKNOWN level for null level lines
- add grafana example
FT: manually with docker env
> AMBARI-24943. Log Feeder: log level filter does not have any affect if level field is null

- ambari-logsearch-web/src/app/components/log-level/log-level.component.html
- ambari-logsearch-web/src/app/components/log-level/log-level.component.spec.ts
- ambari-logsearch-web/src/app/components/service-logs-table/service-logs-table.component.html
Simple edge case handling. It is a fallback solution when the `level` property is missing.
It was tested manually and by unit tests:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 292 of 292 SUCCESS (9.154 secs / 9.048 secs)
✨  Done in 35.93s.
```
> [AMBARI-24945] [Log Search UI] Handling null or undefined value in log's level property.

- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/common/LogFeederConstants.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/common/LogFeederSolrClientFactory.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/ApplicationConfig.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/LogFeederProps.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputSolr.java
- ambari-logsearch-logfeeder/src/test/java/org/apache/ambari/logfeeder/common/LogFeederSolrClientFactoryTest.java
- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/conf/LogSearchConfigApiConfig.java
- ambari-logsearch-server/src/main/resources/logsearch.properties
- docker/test-config/logsearch/logsearch.properties
- jenkins/containers/docker-logsearch-portal/conf/logsearch.properties
- add discover flag to create LBHttpSolr clients by Solr Cloud client, after the client is created, the Solr cloud client is closed. (so will close ZK connection)
use case:
- external solr is used for ambari cluster (logfeeders are outside)
- ambari cannot get the solr urls through command.json, then it is a bit problematic to provide all the solr urls manually, also can be problematic when the hosts will change
-> use solr zookeeper address which will fetch the base urls (it has done once, so if the hosts will change, logfeeders should be restarted)
Added some cleanups (missing properties + renaming)
with docker and vagrant env locally
Please review @g-boros
> AMBARI-24949. Log Search: add Solr node discovery + small cleanups

- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/loglevelfilter/LogLevelFilterHandler.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/util/DateUtil.java
Logfeeder sets the default timezone to GMT at start up. Most service logs' logtime are in os timezone. If os timezone is set to other than UTC Logfeeder does not convert the logtime values to UTC when sending the log entry to Solr and Logsearch portal shows invalid log time values.
Fix: 
* Remove explicitly set the default time zone to GMT. This case the default time zone going to be the os time zone
Or it can be overridden by JVM option.
* Remove unused `dateToString` method.
Manually:
1. Deploy Ambari and a cluster: Zookeeper, Infra-Solr, Logsearch
2. Set the time zone en each node to America/Chicago: 
```timedatectl set-timezone America/Chicago```
3. Restart Amabari server/agents and all services
4. Check Ambari server log and notice that the log time values are at the new time zone in …
> AMBARI-24950 - Logsearch: use os timezone in Logfeeder

- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/conf/SolrAuditLogPropsConfig.java
- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/conf/SolrMetadataPropsConfig.java
- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/conf/SolrServiceLogPropsConfig.java
- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/dao/SolrSchemaFieldDao.java
- ambari-logsearch-server/src/main/resources/logsearch.properties
- ambari-logsearch-server/src/test/resources/logsearch.properties
- docker/test-config/logsearch/logsearch-https.properties
- docker/test-config/logsearch/logsearch-sso.properties
- docker/test-config/logsearch/logsearch.properties
- jenkins/containers/docker-logsearch-portal/conf/logsearch.properties
Cleanup logsearch property names - use similar prefixes, do not mix it up
with docker env
> AMBARI-24956. Log Search: cleanup audit/service log config name prefixes

- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/common/LogSearchConstants.java
- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/manager/InfoManager.java
show log level filters are enabled or disabled on /info/features endpoint.
Later, it can be used by the UI to disable the log level filter setting, if it cannot be used by BE
with docker env manually
> AMBARI-24959. Log Search: show log level filters are enabled or disabled on /info/features endpoint

- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/conf/LogSearchLdapAuthConfig.java
- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/conf/SecurityConfig.java
- use different ways to get LDAP password for Log Search
right now we are only getting password with these methods for ldap, long term solution will be to create an ambari-logsearch-common module, which will contain secret store methods, those will be used by logfeeder and logsearch as well
not needed, not used feature yet.
> AMBARI-24662. Support non-plain text passwords for LDAP authentication

- ambari-logsearch-logfeeder/pom.xml
- ambari-logsearch-logfeeder/src/main/resources/core-site-examples/abfs-core-site.xml
- ambari-logsearch-logfeeder/src/main/resources/core-site-examples/s3-core-site.xml
- ambari-logsearch-logfeeder/src/main/resources/core-site-examples/wasb-core-site.xml
- pom.xml
Use specific release of hadoop libraries as ABFS is not included in hadoop 3.1.1 version yet
also add some example core-site.xml s
i## How was this patch tested?
manually with created WASB and ABFS(S) storage accounts on Azure
> AMBARI-24833. ABFS (ADLS v2) fs implementation was not included on the classpath

- ambari-logsearch-web/src/app/modules/shared/components/dropdown-list/dropdown-list.component.html
- ambari-logsearch-web/src/app/modules/shared/components/dropdown-list/dropdown-list.component.ts
I removed the bi-direction data binding in dropdown list item, so that the change can be detected in the parent component. Also I changed the way of the selection change in `selectAll` and the `unSelectAll` methods in order to the parent component has chance to detect change(s). 
It was tested manually (checking all the displayed dropdowns selection change) and by unit tests:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 292 of 292 SUCCESS (19.635 secs / 19.439 secs)
```
> [AMBARI-24975] Log Search UI: if there are multiple clusters - selecting one of it does not do anything

- ambari-logsearch-server/src/main/configsets/hadoop_logs/conf/managed-schema
Limit max length of tokenized strings (it is not normal is a tokenized string is too large, but at least filter out them because following can happen on solr side:
```bash
Error: {
"responseHeader":{
"status":400,
"QTime":5},
"error":{
"metadata":[
"error-class","org.apache.solr.common.SolrException",
"root-error-class","org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException"],
"msg":"Exception writing document id 30b6c195-e29b-4ab9-9583-511b3e798461 to the index; possible analysis error: Document contains at least one immense term in field=\"key_log_message\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[91, 111, 119, 110, 101, 114, 58, …
```
> Limit max length of tokens (Solr string)

- k8s/helm-charts/infra-solr/Chart.yaml
- k8s/helm-charts/infra-solr/templates/infra-solr.yaml
- k8s/helm-charts/infra-solr/values.yaml
- k8s/helm-charts/logsearch-helm.sh
- k8s/helm-charts/logsearch/Chart.yaml
- k8s/helm-charts/logsearch/templates/logsearch-configmap.yaml
- k8s/helm-charts/logsearch/templates/logsearch.yaml
- k8s/helm-charts/logsearch/values.yaml
- k8s/helm-charts/zookeeper/Chart.yaml
- k8s/helm-charts/zookeeper/templates/zookeeper.yaml
- k8s/helm-charts/zookeeper/values.yaml
- k8s/localstack/localstack.yaml
- pom.xml
add basic helm charts for logsearch (no logfeeders yet)
added a static localstack definition as well. later if logfeeder will be added, that will be integrated with logfeeder cloud mode deployment
./logsearch-helm.sh install
for purge:
./logsearch-helm.sh delete
> Add basic helm charts for Log Search (developement)

- .gitignore
- Makefile
- ambari-logsearch-config-json/src/main/java/org/apache/ambari/logsearch/config/json/model/inputconfig/impl/ConditionsImpl.java
- ambari-logsearch-config-json/src/main/java/org/apache/ambari/logsearch/config/json/model/inputconfig/impl/FieldsImpl.java
- ambari-logsearch-config-json/src/main/java/org/apache/ambari/logsearch/config/json/model/inputconfig/impl/FilterGrokDescriptorImpl.java
- ambari-logsearch-config-json/src/main/java/org/apache/ambari/logsearch/config/json/model/inputconfig/impl/InputConfigImpl.java
- ambari-logsearch-config-json/src/main/java/org/apache/ambari/logsearch/config/json/model/inputconfig/impl/InputS3FileDescriptorImpl.java
- ambari-logsearch-docs/pom.xml
- ambari-logsearch-docs/src/main/java/org/apache/ambari/logsearch/doc/LogSearchDocumentationGenerator.java
- ambari-logsearch-docs/src/main/java/org/apache/ambari/logsearch/doc/ShipperConfigDescriptionDataHolder.java
- ambari-logsearch-docs/src/main/resources/docs.md
- ambari-logsearch-docs/src/main/resources/templates/shipper_configurations.md.ftl
- ambari-logsearch-logfeeder-plugin-api/src/main/java/org/apache/ambari/logfeeder/plugin/output/Output.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/conf/LogFeederProps.java
- ambari-logsearch-logfeeder/src/main/java/org/apache/ambari/logfeeder/output/OutputSolr.java
- ambari-logsearch-server/pom.xml
- docs/about.md
- docs/add_new_input.md
- docs/api-docs/logsearch-swagger.yaml
- docs/cloud_mode.md
- docs/docs.md
- docs/getting_started.md
- docs/index.md
- docs/logfeeder_properties.md
- docs/logsearch_properties.md
- docs/schema_fields.md
- docs/shipper_configurations.md
- mkdocs.yml
- pom.xml
- fix some docs
- generate output shipper configs as well
- add mkdocs support
- put javadoc + rest api doc as well to generated site
- add markdown skeletons (i will need to fill those + add nice pictures)
note: probably we will use docker for mkdocs build, right now it is expected to be installed
full test: `make serve-site`, it can take long because of 2 web build, if modules are already installed then its enough to run: `make javadoc`, `make prop-docs-only` then `make serve-site-only`
Please review @g-boros
> AMBARI-23456. Add mkdocs support & markdown skeletons

- ambari-logsearch-web/src/app/components/action-menu/action-menu.component.html
- ambari-logsearch-web/src/app/components/action-menu/action-menu.component.ts
- ambari-logsearch-web/src/app/components/log-index-filter/log-index-filter.component.ts
Save button state: Changing the enable/disable condition to a more direct one.
Overrides checking with "select all": checking the component hasOverrides prop too.
It was tested manually and by unit tests:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 295 of 295 SUCCESS (11.208 secs / 11.037 secs)
✨  Done in 40.82s.
```
> [AMBARI-25012] Log Search UI: cannot save filters + select all selecting the ovirrides as well

- ambari-logsearch-web/src/app/components/timezone-picker/timezone-picker.component.html
Removing the old `afterViewInit` handler, because the map is initialised within the new component.
It was tested manually by opening console and checking time zone modal functionality, also by unit tests:
```
Chrome 70.0.3538 (Mac OS X 10.13.6): Executed 295 of 295 SUCCESS (8.474 secs / 8.197 secs)
```
> [AMBARI-25016] [Log Search UI] There is console error about TimeZonePicker initialisation

- ambari-logsearch-web/src/app/components/filters-panel/filters-panel.component.ts
- ambari-logsearch-web/src/app/components/search-box/search-box.component.html
- ambari-logsearch-web/src/app/components/search-box/search-box.component.spec.ts
Set `isChecked` prop to `false` when we create the list for the available filter fields in order to prevent the auto selection. 
It was tested manually, loading the screens (audit and service logs screens) and via unit tests:
```
Chrome 70.0.3538 (Mac OS X 10.13.6): Executed 295 of 295 SUCCESS (8.843 secs / 8.668 secs)
```
> [AMBARI-25015] [Log Search UI] Cluster search param added by default when the app loaded on service logs screen

- ambari-logsearch-web/src/app/app.module.ts
- ambari-logsearch-web/src/app/classes/models/store.ts
- ambari-logsearch-web/src/app/components/action-menu/action-menu.component.html
- ambari-logsearch-web/src/app/components/action-menu/action-menu.component.spec.ts
- ambari-logsearch-web/src/app/components/action-menu/action-menu.component.ts
- ambari-logsearch-web/src/app/components/filter-history-manager/filter-history-manager.component.html
- ambari-logsearch-web/src/app/components/filters-panel/filters-panel.component.html
- ambari-logsearch-web/src/app/components/menu-button/menu-button.component.html
- ambari-logsearch-web/src/app/components/menu-button/menu-button.component.ts
- ambari-logsearch-web/src/app/components/top-menu/top-menu.component.spec.ts
- ambari-logsearch-web/src/app/components/top-menu/top-menu.component.ts
- ambari-logsearch-web/src/app/modules/app-load/services/app-load.service.ts
- ambari-logsearch-web/src/app/modules/shared/components/dropdown-list/dropdown-list.component.html
- ambari-logsearch-web/src/app/modules/shared/components/dropdown-list/dropdown-list.component.less
- ambari-logsearch-web/src/app/modules/shared/components/dropdown-list/dropdown-list.component.ts
- ambari-logsearch-web/src/app/modules/shipper/shipper-routing.module.ts
- ambari-logsearch-web/src/app/services/api-feature.guard.ts
- ambari-logsearch-web/src/app/services/http-client.service.ts
- ambari-logsearch-web/src/app/services/meta-data-api-feature.guard.ts
- ambari-logsearch-web/src/app/services/storage/reducers.service.ts
- ambari-logsearch-web/src/app/store/actions/api-features.actions.ts
- ambari-logsearch-web/src/app/store/effects/api-features.effects.ts
- ambari-logsearch-web/src/app/store/reducers/api-features.reducers.ts
- ambari-logsearch-web/src/app/store/selectors/api-features.selectors.ts
- ambari-logsearch-web/src/assets/i18n/en.json
- getting the information from the server
- disable/enable the buttons pointing to the related feature
- disable routing of shipper config when the meta_data pattern editor disabled
- disable to show log index filter settings when the log levels filter disabled
- adding extra server response handling: 503 means the feature is turned off
It was tested manually (by changing the states from console) and by unit tests:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 295 of 295 SUCCESS (12.633 secs / 12.486 secs)
✨  Done in 45.73s.
```
> [AMBARI-24896] [Log Search UI] Turn off features in the client when it is not available on backend

- ambari-logsearch-web/src/app/components/logs-container/logs-container.component.html
I added the missing input parameter to the `AuditLogsEntries` component.
It was tested manually (checking the time zone change too) and by unit tests:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 295 of 295 SUCCESS (13.183 secs / 13.057 secs)
✨  Done in 49.18s.
```
> [AMBARI-25026] [Log Search UI] Audit log list: missing event time value in the log list

- ambari-logsearch-logfeeder-plugin-api/src/main/java/org/apache/ambari/logfeeder/plugin/filter/Filter.java
add new check for the Filter object (in plugin api), if the field name is not too long and contains spaces, lowercase the string, replaces spaces with underscore, then add ws_ prefix to it, to make a dynamic field from it
note: i added 2 functions that are similar that we have in string utils, but i implemented them in order to not include the dependency in the plugin api
manually with docker env - added new fields to ambari audit and see what happens
> AMBARI-25083. Fallback to use dynamic field 'ws_*' if new field name contains whitespace

- ambari-logsearch-web/src/app/modules/shared/components/dropdown-button/dropdown-button.component.html
- ambari-logsearch-web/src/app/modules/shared/components/dropdown-button/dropdown-button.component.ts
- ambari-logsearch-web/src/app/modules/shared/components/filter-dropdown/filter-dropdown.component.spec.ts
- ambari-logsearch-web/src/app/modules/shared/components/filter-dropdown/filter-dropdown.component.ts
- ambari-logsearch-web/src/app/modules/shipper/components/shipper-configuration/shipper-configuration.component.spec.ts
- ambari-logsearch-web/src/app/modules/shipper/components/shipper-configuration/shipper-configuration.component.ts
- ambari-logsearch-web/src/app/modules/shipper/components/shipper-service-configuration-form/shipper-service-configuration-form.component.html
- ambari-logsearch-web/src/app/modules/shipper/components/shipper-service-configuration-form/shipper-service-configuration-form.component.less
- ambari-logsearch-web/src/app/modules/shipper/components/shipper-service-configuration-form/shipper-service-configuration-form.component.ts
- ambari-logsearch-web/src/app/modules/shipper/directives/validator.directive.ts
- docs/cloud_mode.md
Instead of using text input for the `Component Name` in validation form, I added a dropdown which is populated from the config JSON from the `Configuration` form.
If the JSON is not valid, or there is no component under the `input` property of the configuration, the dropdown is disabled.
It was tested manually (because of the changes of the `DropdownComponent` I tested all the screens) and by unit tests:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 295 of 295 SUCCESS (12.378 secs / 12.256 secs)
✨  Done in 43.39s.
```
> [AMBARI-25028] [Log Search UI] Populate `Component Name` in validator

- Makefile
- ambari-logsearch-docs/pom.xml
- ambari-logsearch-docs/src/main/java/org/apache/ambari/logsearch/doc/LogSearchDocumentationGenerator.java
- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/rest/ServiceLogsResource.java
- docs/api-docs/logsearch-swagger.yaml
- make rest api doc generation configurable (because every for every doc generation, the result is different)
- some doc fixes: operationId duplications in swagger doc
update-rest-api-docs
> AMBARI-23456. Make rest api doc generation configureable & doc fixes

- ambari-logsearch-it/src/test/java/org/apache/ambari/logsearch/solr/search/SearchServiceLogsTest.java
- ambari-logsearch-server/src/main/configsets/audit_logs/conf/managed-schema
- ambari-logsearch-server/src/main/configsets/hadoop_logs/conf/managed-schema
Logsearch should index keywords without the ending periods(.).
E.g : Log message : `Caught exception checkIn.`. Message filters were not able to filter the logs with partial text `checkIn` but only with `checkIn.`
UTs passed
Manually:
1. Deploy Ambari and a cluster: logsearch, ambri infra, zk
2. Login to logsearch ui
3. Search for terms with and without punctuation
> AMBARI-25090 - Logsearch should index keywords without the ending periods(.)

- ambari-logsearch-server/src/main/java/org/apache/ambari/logsearch/conf/SecurityConfig.java
ambari-logsearch-portal server cannot startup.
After spring-boot upgrade from 2.0.6.RELEASE to 2.1.5.RELEASE, due to the change of class LdapAutoConfiguration, spring need the LdapTemplate bean during startup.
The full error log please see issue [AMBARI-25992](https://issues.apache.org/jira/browse/AMBARI-25992).
local install and test this fix in local cluster.
(Please explain how this patch was tested. Ex: unit tests, manual tests)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)
> AMBARI-25992: logsearch-portal cannot startup due to spring-boot-autoconfigure upgrade
